### ISSUE TITLE
Error initializing database

### ISSUE THREAD

**Issue by jbrucker** [NokKbl/khubkhao-recommender#37]
I followed the instructions for installing your app locally
(after corrections for previous issues) but on the step:
```
python manage.py loaddata seed.json
```
it throws the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/python.py", line 100, in Deserializer
    data[Model._meta.pk.attname] = Model._meta.pk.to_python(d.get('pk'))
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py", line 945, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'cate1' value must be an integer."]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/loaddata.py", line 168, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/json.py", line 69, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/python.py", line 102, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), None)
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/projects/FoodRecommender/khubkhaoapp/fixtures/seed.json': ["'cate1' value must be an integer."]: (khubkhaoapp.category:pk=cate1) field_value was 'None'
```

**Comment by Driveiei** [comment]
Your version of repository need to be up-to-date. We've already fixed it yesterday. We apologize for late fix.
Click this link for fix details => [Fix details](https://github.com/NokKbl/khubkhao-recommender/pull/33/files)
